name: Keep Replit Bot Alive

on:
  schedule:
    - cron: '*/2 * * * *'  # Setiap 2 menit
  workflow_dispatch:       # Bisa dijalankan manual juga

jobs:
  ping-replit:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Replit Bot
        run: curl -s https://683ab69e-f79c-403a-887a-b9d575e407a7-00-3awk0ge733zzm.sisko.replit.dev/
